junit-team/junit4

pom.xml
Saw that maven-surefire-plugin could be upgraded to a newer version. Verified `mvn clean install` still runs successfully.
=> Upgrade maven-surefire-plugin to latest version

src/main/java/org/junit/rules/Timeout.java
Javadoc for Timeout class should use Timeout.millis(long) instead of deprecated Timeout(int) constructor
=> Use Timeout.millis(long) in javadoc for Timeout class

CONTRIBUTING.md
The Eclipse Foundation requires that all contributors agree to these
terms so that Eclipse can continue to ship with Eclipse.
=> EPL agreement will be shown for new pull requests

src/main/java/org/junit/experimental/categories/Categories.java, src/main/java/org/junit/runners/parameterized/BlockJUnit4ClassRunnerWithParameters.java, src/test/java/org/junit/runners/parameterized/BlockJUnit4ClassRunnerWithParametersTest.java, src/test/java/org/junit/tests/AllTests.java, src/test/java/org/junit/tests/experimental/categories/CategoriesAndParameterizedTest.java
Couldn't see any reason why we should remove annotations like
`@Category` from the child runners of parameterized tests. Now the
`Categories` runner can handle parameterized tests.
=> Provide all annotations except RunWith. Fixes #751

pom.xml
Upgraded all plugins to the latest available version. Additionally, I added version numbers for a couple which didn't set an explicit version number.
I haven't tested that all plugins still work as expected, since some of them are a bit tricky for me to check. Notable examples are the release- and gpg-plugin. I have verified that `mvn clean install` runs succesfully.
=> Upgrade plugins to latest version

pom.xml
The old maven replacer plugin was configured with a relative link to the source path.
This caused a failure of
mvn -f path-to-junit/pom.xml
The modified pom file uses the `project.build.sourceDirectory` property, which solves this problem.
=> Let maven replacer plugin use sourceDirectory property.

src/site/fml/faq.fml
I've updated answer as discussed on JUnit's Yahoo! Group. 
@dsaff,  I think it is now under ~100 columns.
@kcooney, is this pull request now submitted against junit-team/junit?
UPDATED ANSWER:
If you are using JDK 1.3 or higher, you can use reflection to subvert the access control mechanism with the aid of the <a href="http://sourceforge.net/projects/privaccessor/">PrivilegedAccessor</a>. For details on how to use it, read <a href="http://www.onjava.com/pub/a/onjava/2003/11/12/reflection.html">this article</a>.
If you are using JDK 1.6 or higher and you annotate your tests with @Test, you can use <a href="http://dp4j.com">Dp4j</a> to inject reflection in your test methods. For details on how to use it, see <a href="http://dp4j.com/testscript">this test script</a>.
=> Updated answer to question in faq.html

src/site/xdoc/index.xml
Added prominent link to the project's license.
This patch fixes #1162.
Signed-off-by: Allon Mureinik <mureinik@gmail.com>
=> License link on junit.org

src/main/java/org/junit/rules/ExpectedException.java
Just two minor fixes: missing space in code snippet and typo in `ExpectedException`'s JavaDoc.
=> Fix typo and formatting in JavaDoc

src/main/java/org/junit/rules/ExpectedException.java
This small PR will allow for the `ExpectedException` rule to be used in a more fluent manner.
```java
thrown.expect(IllegalArgumentException.class).expectMessage("Not a valid argument");
```
May need updating on https://github.com/pablisco/hamcrest-junit too
=> Fluent expectations for ExpectedException

src/main/java/org/junit/runner/JUnitCommandLineParseResult.java
at org.junit.runner.JUnitCommandLineParseResult
According to https://github.com/junit-team/junit4/issues/1271
=> Replace ArrayList for primitive array in copyArray method

src/test/java/junit/tests/runner/ResultTest.java
When an ObjectOutputStream instance wraps an underlying ByteArrayOutputStream instance,
it is recommended to flush or close the ObjectOutputStream before invoking the underlying instances's toByteArray(). Although in this case, this is not strictly necessary because the writeObject method is invoked right before toByteArray, and writeObject internally calls flush/drain.  However, it is a good practice to call flush/close explicitly as mentioned for example [here](http://stackoverflow.com/questions/2984538/how-to-use-bytearrayoutputstream-and-dataoutputstream-simultaneously-java).
This pull request adds a flush method before calling toByteArray().
=> Closing ObjectOutputStream before calling toByteArray on the underlying ByteArrayOutputStream

src/test/java/org/junit/tests/experimental/AssumptionTest.java
Use a try/catch block instead of the attribute 'expected' of the @Test annotation.
See bug #1290.
See discussion on #1289.
=> refactor  AssumptionTests

pom.xml, src/test/java/org/junit/tests/experimental/AssumptionTest.java
Mvn test output is now more detailed and helpful.
> Fix mvn surefire config: force surefire-junit47 as the surefire provider
> Previously surefire-junit3 was used.
> See also https://maven.apache.org/surefire/maven-surefire-plugin/examples/providers.html
Before:
```
-------------------------------------------------------
T E S T S
-------------------------------------------------------
Running org.junit.tests.AllTests
Tests run: 940, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 8.58 sec - in org.junit.tests.AllTests
Results :
Tests run: 940, Failures: 0, Errors: 0, Skipped: 0
```
After:
```
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ junit ---
-------------------------------------------------------
T E S T S
------------------------------------------------------- …
```
=> Fix mvn surefire config: better test output

pom.xml
As discussed in #1292 
(see https://github.com/junit-team/junit4/pull/1292#issuecomment-219239388)
=> add hamcrest-library as a test dependency

src/main/java/org/junit/rules/RuleChain.java, src/test/java/org/junit/rules/RuleChainTest.java
By throwing IllegalArgEx from around(),
we allow for better feedback to the final user,
as the stacktrace will point to the exact line where the null rule is declared.
Previously the stacktrace would have been something like this:
```
java.lang.NullPointerException
at org.junit.rules.RunRules.applyAll(RunRules.java:26)
at org.junit.rules.RunRules.<init>(RunRules.java:15)
at org.junit.rules.RuleChain.apply(RuleChain.java:96)
at org.junit.rules.RunRules.applyAll(RunRules.java:26)
at org.junit.rules.RunRules.<init>(RunRules.java:15)
at org.junit.runners.BlockJUnit4ClassRunner.withTestRules(BlockJUnit4ClassRunner.java:424)
at org.junit.runners.BlockJUnit4ClassRunner.withRules(BlockJUnit4ClassRunner.java:378)
at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:29 …
```
=> RuleChain#around should not allow null args

src/main/java/org/junit/runners/model/MultipleFailureException.java
I fixed the way MultipleFailureException prints the stacktraces. Now, when multiple exceptions are found, the stacktrace for each exception is printed
=> Fix StackTrace printing when multiple exceptions occur (#1238)

src/main/java/org/junit/runner/Description.java, src/main/java/org/junit/runners/ParentRunner.java, src/test/java/org/junit/tests/running/classes/AllClassesTests.java, src/test/java/org/junit/tests/running/classes/parent/ParentRunnerClassLoaderTest.java, src/test/java/org/junit/tests/running/classes/parent/TestWithClassRule.java
When junit.jar located in one ClassLoader but runing tests in another `ParentRunner` can lost information about run class. For example if use `@ClassRule` and request test class(`org.junit.runner.Description#getTestClass`) we can get null, because `ParentRunner` instead of set Class as is to `Description` tranform it to class name string, as result `org.junit.runner.Description#getTestClass` execute `Class.forName` and can't find test class.
Spring-test fail with exception if we try use `SpringClassRule`
```
java.lang.NullPointerException
at org.springframework.test.context.junit4.rules.SpringClassRule.validateSpringMethodRuleConfiguration(SpringClassRule.java:186)
at org.springframework.test.context.junit4.rules.SpringClassRule.apply(SpringClassRule.java:134)
at …
```
=> Bug: ParentRunner lost test Class from a separate class loader

pom.xml, src/main/java/org/junit/experimental/results/ResultMatchers.java, src/test/java/org/junit/tests/experimental/results/ResultMatchersTest.java
It should *not* match when the given PrintableResult has no failures.
Please note that this change replaces the dependency hamcrest-core with hamcrest-library. I'm not sure if you are happy with that. If you are, we probably also need to update another couple of lines in the pom, see e.g. https://github.com/junit-team/junit4/blob/master/pom.xml#L308
=> Fix ResultMatchers#hasFailureContaining

src/main/java/org/junit/ClassRule.java, src/main/java/org/junit/Rule.java
In the javadoc of Rule and ClassRule, it says field rules are applied before method rules. Actually, method rules are applied before field rules.
=> Fix incorrect javadoc of the Rule running order

src/main/java/junit/runner/BaseTestRunner.java
Fixes #1213, not by adding the doPrivileged, but by coping with lack of access to the file by pretending it doesn't exist.
=> Catch SecurityException in addition to IOException.

src/main/java/junit/runner/TestRunListener.java
Remove unnecessary modifiers "public" for TestRunListener interface because all abstract, default, and static methods in an interface are implicitly public, so you can omit the public modifier.
Here is specified: [Java Doc About Interface Definition](http://docs.oracle.com/javase/tutorial/java/IandI/interfaceDef.html)
=> Remove unnecessary modifiers "public" for TestRunListener interface

src/main/java/junit/runner/BaseTestRunner.java, src/test/java/junit/samples/ListTest.java
Remove unnecessary boxing on ListTest because Java creates an Integer object from `i` and adds to the object `fFull`
Reference:
[`Autoboxing and Unboxing`](https://docs.oracle.com/javase/tutorial/java/data/autoboxing.html)
=> Remove unnecessary boxing on ListTest

src/test/java/junit/samples/ListTest.java
- Change from protected to private `fEmpty` and `fFull` lists, because there is no need to keep accessible from the package and subclass
- Remove unnecessary boxing on `fFull.remove()` because Java creates an Integer object from `i` and adds to the object `fFull`
- Remove main method from ListTest.java
- Rename `fEmpty` to `emptyList`
- Rename `fFull` to `fullList`
- Remove extra blank line
- Change `assertTrue()` for `assertEquals()` on `testElementAt()` method
[Controlling Access to Members of a Class](https://docs.oracle.com/javase/tutorial/java/javaOO/accesscontrol.html)
[Autoboxing and Unboxing](https://docs.oracle.com/javase/tutorial/java/data/autoboxing.html)
=> Set private the lists fEmpty, fFull and remove unnecessary boxing on ListTest

src/main/java/org/junit/rules/ExpectedException.java
- Change reference of javadoc from `org.junit.Assert.ThrowingRunnable` to `org.junit.function.ThrowingRunnable` on `ExpectedException`
=> Change javadoc reference of ThrowingRunnable on ExpectedException

src/main/java/org/junit/runners/model/MultipleFailureException.java
In format strings, it is generally preferable better to use %n, which will produce the platform-specific line separator.
=> Optimize string format

src/main/java/org/junit/internal/matchers/ThrowableCauseMatcher.java, src/main/java/org/junit/rules/ExpectedException.java
The previous generics (Matcher<? extends Throwable>) would not allow
you do use matchers on Object, like notNullValue().
Fixes #1073
=> Change generics on ExpectedException.expectCause().

src/site/fml/faq.fml
The link to the list of xUnit frameworks on xprogramming.com is dead. A more complete and up-to-date list can be found on wikipedia.
=> Fix dead link to xUnit frameworks in FAQ

src/main/java/org/junit/rules/TemporaryFolder.java, src/test/java/org/junit/rules/TemporaryFolderUsageTest.java
that include path separator characters. The overload of newFolder() that
supports passing in multiple strings still does not allow path separators.
=> Update TemporaryFolder.newFolder(String) to support passing in paths

src/main/java/org/junit/experimental/categories/Categories.java, src/test/java/org/junit/experimental/categories/CategoryTest.java
Note that this constructor was removed in #503
=> Add public CategoryFilter constructor that was removed in JUnit 4.12

src/main/java/org/junit/runners/model/FrameworkField.java, src/main/java/org/junit/runners/model/FrameworkMember.java, src/main/java/org/junit/runners/model/FrameworkMethod.java, src/main/java/org/junit/runners/model/TestClass.java, src/test/java/org/junit/tests/running/methods/AnnotationTest.java
This is one possible fix for #1411
The other possible fix is #1412
=> Ignore bridge methods when scanning for annotated methods.

src/main/java/org/junit/runners/BlockJUnit4ClassRunner.java, src/main/java/org/junit/runners/ParentRunner.java, src/test/java/org/junit/tests/running/classes/ParentRunnerTest.java, src/test/java/org/junit/tests/running/classes/SuiteTest.java
This fixes a regression in JUnit 4.12.
=> Classes annotated with @RunWith(Suite.class) do not need to be public.

src/main/java/org/junit/rules/ExternalResource.java
So that clients don't have to try-catch-and-rethrow explicitly checked exceptions.
You may not be happy with changing the signature, though :(
=> ExternalResource: declare after() to throw Exception

src/main/java/org/junit/runners/BlockJUnit4ClassRunner.java
Extract to local variable the result of getExpectedException(), thus saving one extra call.
=> Refactor BlockJUnit4ClassRunner.possiblyExpectingExceptions

src/main/java/org/junit/internal/runners/statements/RunAfters.java, src/main/java/org/junit/internal/runners/statements/RunBefores.java, src/main/java/org/junit/runners/Parameterized.java, src/main/java/org/junit/runners/parameterized/BlockJUnit4ClassRunnerWithParameters.java, src/test/java/org/junit/tests/running/classes/ParameterizedTestTest.java
This PR addresses issue #45.
Some `@ParamRule` could also be introduced.
=> @BeforeParam/@AfterParam for Parameterized runner

src/main/java/org/junit/internal/requests/ClassRequest.java, src/main/java/org/junit/runners/ParentRunner.java
In almost all cases, this is more efficent, especially if there is any
contention on the locks.
=> Replace uses of synchronized(something) with ReentrantLock.

src/main/java/org/junit/rules/ExpectedException.java
Is there any harm in making this method public?
I have a base class for our test classes that has both an ExpectedException rule and a Verifier rule. The problem is that I don't want to run the Verifier if any exception is expected. So this is my current solution:
```
public abstract class TestBase {
private Method isAnyExceptionExpected;
public TestBase() throws Exception {
this.isAnyExceptionExpected = ExpectedException.class.getDeclaredMethod("isAnyExceptionExpected");
this.isAnyExceptionExpected.setAccessible(true);
}
@Rule
public ExpectedException thrown = ExpectedException.none();
@Rule
public Verifier verifier = new Verifier() {
@Override
public void verify() {
try {
if (!(boolean) isAnyExceptionExpected.invoke(thrown)) {
verifyStuff();
verifyOtherStuff();
alsoVerifyThis();
}
} …
```
=> Made ExpectedExceptio.isAnyExceptionExpected public.

src/main/java/org/junit/Assert.java, src/test/java/org/junit/tests/assertion/AssertionTest.java
=> fix assertEquals() if toString() returns null

src/test/java/org/junit/tests/assertion/AssertionTest.java
That was discovered while discussing #1454, so I would like it be more consistent.
=> consistent exception testing in AssertionTest

src/main/java/org/junit/internal/Throwables.java, src/test/java/org/junit/internal/StackTracesTest.java
=> Support suppressed exceptions when trimming stack trace

src/main/java/org/junit/runners/Parameterized.java, src/test/java/org/junit/tests/running/classes/ParameterizedTestTest.java
=> Handle AssumptionViolatedException in @Parameters method

src/main/java/org/junit/runners/parameterized/BlockJUnit4ClassRunnerWithParameters.java, src/test/java/org/junit/runners/parameterized/BlockJUnit4ClassRunnerWithParametersTest.java
For private @Parameter fields is users get an exception like "java.lang.IllegalAccessException: Class ... can not access a member of class X with modifiers private" The new message "Cannot set parameter 'parameter'. Ensure that the the field 'parameter' is public." tells the user what they should do.
The reason for adding this feature is the Stackoverflow question https://stackoverflow.com/questions/44522046/reflection-exception-in-parameterized-junit-test-using-array-parameter/44522988
=> Provide helpful message if parameter cannot be set.

src/main/java/org/junit/rules/TemporaryFolder.java
Fixed a no-op loop that could occur after we fail to delete one of the files under the current TemporaryFolder. I thought it is better to delete as many files as possible before returning back to TemporaryFolder#delete() caller function.
=> Fix TemporaryFolder deletion after test execution

src/main/java/org/junit/rules/ExpectedException.java
The change was not binary compatible with JUnit 4.12.
In addition, the preferred way to check for exceptions
in JUnit 4.13 is with Assert.assertThrows() so we will
be not adding new major features to ExpectedException.
This reverts commit 1db00d5a965951ea3667480a96467b43a80823c1.
=> Revert "Fluent expectations for ExpectedException".

src/main/java/org/junit/Assert.java, src/main/java/org/junit/function/ThrowingRunnable.java, src/main/java/org/junit/rules/ExpectedException.java, src/test/java/org/junit/tests/assertion/AssertionTest.java
as suggested again in #1496, Hopefully it helps with having a release sooner.
The important part is making a release, it's not a big deal if there is 1 or 2 methods.
=> rename expectThrows() to assertThrows()

src/main/java/org/junit/rules/ExpectedException.java, src/test/java/org/junit/rules/ExpectedExceptionTest.java
A test that should fail because of ErrorCollector may not fail when this test throws an exception that is expected by ExpectedException.
Fixes #1466.
=> Recommend to set order for ExpectedException

src/main/java/org/junit/rules/ExpectedException.java
The method Assert.assertThrows provides a nicer way for verifying exceptions. In addition the use of ExpectedException is error-prone when used with other rules like TestWatcher because the order of rules is important in that case.
`assertThrows` is in any way better than `ExpectedException`:
- the code that throws the exception can be exactly specified
- no dependency on rule ordering
- the exception is exposed so that any of its properties can be checked
`assertThrows` is only easy to use with Java 8. For older versions of Java you need boiler-plate code for creating a `ThrowingRunnable`
=> Deprecate rule ExpectedException

src/test/java/org/junit/internal/runners/statements/FailOnTimeoutTest.java
Improve readability of tests because the assert explicitly wraps the statement that throws the exception.
=> Use assertThrows

src/test/java/org/junit/tests/running/core/MainRunner.java
This method was removed in Java 10 (see
https://bugs.openjdk.java.net/browse/JDK-8189750).
Fixes #1522
=> Simplify NoExitSecurityManager.

src/main/java/org/junit/internal/runners/statements/FailOnTimeout.java, src/test/java/org/junit/internal/runners/statements/FailOnTimeoutTest.java
This was seen with heavy impact because Spring uses the ThreadGroupContext to store internal information.
The thread group created for handling the timeout of tests is never destroy, so the `main` thread group keeps a reference to all timeout groups created during the tests. This causes the threadGroup to remain in memory, and all of its context along with it.
This change avoids that by destroying the ThreadGroup after the test.
However, in some cases (like if a thread from the group is hanged), the ThreadGroup destruction fails. In that case, the exception is ignored so the behavior is not changed.
=> ThreadGroup instance leaked when using Timeout rule

.travis.yml
As of June 18th 2018, Maven Central supports TLS 1.2 only. Therefore we cannot install dependencies with JDK 6 anymore. As a workaround we switch in each build temporarily to JDK 8 for downloading the dependencies. Afterwards we restore the desired JDK and build System Rules with it.
=> Download dependencies with JDK 8

src/site/xdoc/index.xml
This project moved from Google Code to GitHub.
Fixes #1540.
=> Fix link to JUnit Toolbox

src/main/java/org/junit/runners/Parameterized.java
Since 7111b9621997f6c660687b8ac04003398343ee3a we support assumptions in
@Parameters methods. This commit adds a description of this feature to
the Javadoc of the Parameterized runner so that people can discover the
new feature more easily.
=> Add assumption support to Javadoc of Parameterized

src/main/java/org/junit/experimental/max/MaxHistory.java
- Used a finally block to close the stream.
- fix https://github.com/junit-team/junit4/issues/1556
=> Close `ObjectOutputStream` in a finally clause

doc/ReleaseNotes4.12.md
We forgot to add it before we released JUnit 4.12. I think it may be still helpful when someone reads the old release notes.
=> Add description for pull request #876

src/main/java/org/junit/rules/TemporaryFolder.java
- Simplify `If` statements in `Double` and `Float` checking methods with of `Assert` class.
=> Replace for with foreach

src/main/java/org/junit/rules/TemporaryFolder.java, src/test/java/org/junit/rules/TemporaryFolderUsageTest.java
When `TemporaryFolder(String path)` or `TemporaryFolder(String... paths)` is
called with a path that matches the path of an existing file then an
`IOException` with a message like "a file with path <path> exists" is
thrown.
=> Improve message if file exists instead of folder 

pom.xml
Prior to this commit, `junit` was derived as the module name from the name of the JAR file. Now, `junit` is set as an explicit module name, stored in the MANIFEST.MF file, to ensure a smooth ride into the modular age for users of JUnit 4.
=> Set 'junit' as `Automatic-Module-Name`

src/main/java/org/junit/runners/BlockJUnit4ClassRunner.java, src/main/java/org/junit/runners/ParentRunner.java, src/test/java/org/junit/tests/running/classes/AllClassesTests.java, src/test/java/org/junit/tests/running/classes/ThreadsTest.java
The thread interrupt status flag is now cleared from `classBlock()` and
`methodBlock()`. The flag is cleared after each test case completes and
after `AfterClass` methods and `ClassRules` have been executed.
Fixes #1365.
---
Originally submitted as #1569.
=> Clear thread interrupt status after each test

src/main/java/org/junit/ClassRule.java, src/main/java/org/junit/Rule.java
Instead of mentioning the now deprecated `RuleChain`, the Javadoc of the
`Rule` and `ClassRule` annotation now contains an example on how to use
the new `order` attribute.
Resolves #1593.
=> Document order attribute of Rule and ClassRule

src/main/java/org/junit/rules/ExpectedException.java
The Javadoc already indicates that it is deprecated.
=> Annotate ExpectedException with @Deprecated.

BUILDING
git clone default is to name cloned path same as repo.git.
=> make junit4 path consistent with clone

src/main/java/org/junit/runners/model/FrameworkField.java, src/main/java/org/junit/runners/model/FrameworkMember.java, src/main/java/org/junit/runners/model/TestClass.java, src/test/java/org/junit/runners/model/TestClassTest.java, src/test/java/org/junit/tests/running/methods/AnnotationTest.java
This commit restores the shadowing behaviour of JUnit 4.12. Some users of JUnit 4 have tests that rely on this behaviour. Their tests would fail with JUnit 4.13.
This commit finally reverts 39b8a92d24e6c81e4fc614cdf13003ce17bbc166. Some parts have already been reverted by ed6813d3bbe2da4d67892f73e641fa80ab4d126e.
=> Restore that fields shadow fields from super class

src/main/java/org/junit/rules/RuleChain.java
The purpose of this rule is no longer the ordering of rules but it can still be used for composing rules into a single rule. Therefore we remove the deprecation.
Fixes #1614.
=> Rewrite Javadoc of RuleChain

.travis.yml
Trusty has support for OpenJDK 6 and other old JDKs.
=> Run tests on Ubuntu Trusty

src/main/java/org/junit/rules/ExpectedException.java
Instead of deprecating the whole class, now only the factory method is
deprecated and points to `assertThrows()`. This will make it easier to
temporarily suppress the exception for codebases that use it
extensively by adding an intermediate factory method of their own.
Resolves #1609.
=> Only deprecate ExpectedException.none()

src/main/java/org/junit/runner/OrderWith.java, src/main/java/org/junit/runner/OrderWithValidator.java, src/main/java/org/junit/runners/ParentRunner.java, src/test/java/org/junit/runner/AllRunnerTests.java, src/test/java/org/junit/runner/OrderWithValidatorTest.java, src/test/java/org/junit/tests/manipulation/OrderableTest.java, src/test/java/org/junit/tests/manipulation/SortableTest.java
=> Never reorder classes annotated with @FixMethodOrder

.travis.settings.xml
We are using Maven 3.1.1 which by default uses HTTP instead of HTTPS for resolving artifacts from Maven Central. Maven Central recently discontinued HTTP support. Therefore the build on Travis started failing. By using an HTTPS mirror of Maven Central the build on Travis will work again.
I chose Google's mirror because Travis uses this mirror by default, too. I did not upgrade to a new version of Maven because there is no newer version with Java 5 support and it should be possible to build JUnit 4 with Java 5 so that we can easily ensure that it works with Java 5.
=> Use Google's Maven Central mirror

src/main/java/junit/runner/Version.java, src/main/java/org/junit/runners/model/FrameworkField.java
Prior to this change, custom runners could make FrameworkMethod
instances, but not FrameworkField instances. This small change
allows for both now, because FrameworkFields constructor has been
promoted to public from package-private.
=> Make FrameworkField ctor public. Fixes #1668

src/main/java/org/junit/Assert.java
In #1141, while [this param named **actual**](https://github.com/junit-team/junit4/pull/1141/files#diff-73eb269f6f932a6bd4cc17c2cfd54571R598) was unwrapped, other params are still wrapped in Double or Float#valueOf.
I consider that its wrapping is necessary for consistency.
=> Explicitly wrap float parameter for consistency

src/main/java/org/junit/Test.java
Provide information about alternatives to the expected parameter which can be used to overcome the limitations of expected.
This is an improvement for JUnit 4.13 to the fix for #806 (84dcb64).
=> Add a link to assertThrows in Javadoc of Test annotation

src/test/java/junit/tests/framework/DoublePrecisionAssertTest.java, src/test/java/junit/tests/framework/FloatAssertTest.java
The issue is that both
```java
assertEquals(1.0, 2.0, 0.0);
```
and
```java
fail();
```
throw an `AssertionFailedError`, so these tests were actually not testing anything...
=> Fix tests for floating point assertions

src/main/java/org/junit/internal/runners/statements/FailOnTimeout.java, src/test/java/org/junit/internal/runners/statements/FailOnTimeoutTest.java
=> Mark ThreadGroups created by FailOnTimeout as daemon groups

doc/ReleaseNotes4.13.2.md, src/main/java/org/junit/internal/runners/statements/FailOnTimeout.java, src/test/java/org/junit/internal/runners/statements/FailOnTimeoutTest.java
This reduces the differences (where possible) when tests are run with a timeout.
Creating a ThreadGroup can cause noticeable differences, for example in code
that uses java.beans.ThreadGroupContext.
=> Only create ThreadGroups if FailOnTimeout.lookForStuckThread is true.

src/site/fml/faq.fml
URL http://ant.apache.org/manual/OptionalTasks/junit.html is dead.  Use
up-to-date URL for documentation of Ant's JUnit task in file 'faq.fml'.
This is similar to commit 24dfdd76 (Fix dead link to the ant task in FAQ
(#1478), 2017-08-08).
----
I've stumbled by accident upon my fork of junit4 repository, which I created way back in 2017, and while trying to remember what I've done with it (PR #1478, commit 24dfdd76), I have discovered that a similar dead link is present in more places. So here's a fix for that.
=> Fix dead link to the Ant task in faq.fml

src/main/java/org/junit/internal/runners/ErrorReportingRunner.java
The background is that we run this code through a compiler that complains about unused variables.
As I see it, it doesn't really make sense for the compiler to complain about an unused variable in this case. But given that it does, this could work around the problem for us.
Since there's no benefit to normal users from this PR, I'd also be OK with just maintaining a patch on our end. It's not hard; I just expect to be asked "Did you try to upstream this?" and so I'd like to be able to answer "yes" :)
---
In all this, I'm assuming that the looping _is_ intentional. The other possibility would be that we're actually supposed to call `addChild` only once. But I'm assuming that the `Description` returned by `getDescription()` is supposed to include one entry for each `Description` that will …
=> Use an indexed for loop to avoid defining an unused variable.

src/test/java/org/junit/tests/experimental/theories/runner/WithParameterSupplier.java
Capture unused Theories creation into an unused variable (ErrorProne's CheckReturnValue can be configured to require all constructor calls to be used).
=> Fix unused object creation in WithParameterSupplier

pom.xml
Java 20 has [dropped](https://www.oracle.com/java/technologies/javase/20-relnote-issues.html#JDK-8173605) support for 1.7 as the source and target versions.  This pull request does something similar to commit 66083734d13aa67e616f3c4b429c019c5992bba0 to allow the project to be built with e.g. JDK 21.
This is perhaps also a prerequisite of #1767.
=> pom.xml: Fix build for Java 20 and above

.github/workflows/main.yml, .github/workflows/settings.xml, doc/building-junit.txt, pom.xml
see https://github.com/junit-team/junit5/issues/4483
=> Migrate to Maven Central Publisher Portal
