CONTRIBUTING.md
Fixed some typos and added some useful links.
=> Fixed a typo in step 7 in the quick guide.

src/site/fml/faq.fml
=> Deleted dead faq link.

src/main/java/org/junit/rules/TemporaryFolder.java
=> Fix wrong exception type in JavaDoc

src/main/java/org/junit/internal/runners/ErrorReportingRunner.java
Commits are separate just for the sake of reviewing; needs to be squashed before merging.
This is just a refactoring, no functional changes involved.
=> Refactor ErrorReportingRunner

src/test/java/org/junit/tests/experimental/theories/runner/UnsuccessfulWithDataPointFields.java
https://junit.ci.cloudbees.com/job/JUnit/78/console
#1286
=> Fix broken build for jdk5

src/main/java/org/junit/runner/Request.java
As requested by PR [#1318](https://github.com/junit-team/junit4/issues/1318) added and extra to the description to better suit the return values by this function. 
Lest me know if it requires further tweaking :)
=> Modified the JavaDoc to better suit the returning values of the function Request.filterWith

.gitattributes, .gitignore
This is a replacement for #1183
=> Use Unix-style line endings.

pom.xml
=> Fix cant run our suite of tests in parallel. (#1297)

src/main/java/org/junit/runners/BlockJUnit4ClassRunner.java, src/test/java/org/junit/tests/running/classes/BlockJUnit4ClassRunnerTest.java
=> Call methodBlock() after fireTestStarted()

src/site/fml/faq.fml
Documentation to the ant junit task has been moved to another location.
=> Fix dead link to the ant task in FAQ

pom.xml
=> Generate Javadoc for the junit.* packages.

src/test/java/org/junit/rules/EventCollector.java, src/test/java/org/junit/runner/RequestTest.java
The code was changed by commit 0804ef4cd09b0e94783a9882c60914e22fca5108 but unfortunately the test was not part of the commit. The test is based on Philip Graf's test in pull request #1065.
=> Add test for handling InitializationError

src/test/java/org/junit/rules/ErrorCollectorTest.java, src/test/java/org/junit/rules/EventCollector.java
The array for the Parameterized gives a better overview of the tests.
=> Run ErrorCollectorTest with Parameterized runner

src/test/java/org/junit/rules/ErrorCollectorTest.java
The code did not compile with JDK 5 before.
=> Add explicit type parameters for JDK 5

src/main/java/org/junit/runners/model/FrameworkField.java, src/main/java/org/junit/runners/model/FrameworkMember.java, src/main/java/org/junit/runners/model/FrameworkMethod.java, src/main/java/org/junit/runners/model/TestClass.java, src/test/java/org/junit/tests/running/methods/AnnotationTest.java
=> Shadowed static methods/fields should override parent class behavior.

src/main/java/org/junit/rules/DisableOnDebug.java, src/main/java/org/junit/runners/ParentRunner.java
- merge two if branches with the same implementation (`return true` in the both branches).
- use `Collections.singletonList` instead of `Arrays.asList` since it is only one item.
=> Merge two if branches with the implementation

src/main/java/org/junit/runners/ParentRunner.java, src/test/java/org/junit/rules/ClassRulesTest.java
=> ParentRunner.classRules() returns modifiable List

src/main/java/org/junit/rules/ExternalResource.java
This reverts commit cebbf5e15725b4dc247ac0557f6fa63f475b15af.
=> Revert "ExternalResource: declare after() to throw Throwable (#1421)"

src/main/java/org/junit/Assume.java, src/test/java/org/junit/tests/experimental/AssumptionTest.java
=> Changed the assumeFalse method 

src/main/java/org/junit/internal/Throwables.java, src/test/java/junit/tests/SampleJUnit3Tests.java, src/test/java/org/junit/internal/StackTracesTest.java, src/test/java/org/junit/tests/SampleJUnit4Tests.java
Follow Kevin's idea from ead2fe7ca97e4b0bc013efe0e734e39a45db213c up that sample test classes are stored in a specific container.
=> Extract sample test classes from StackTracesTest

src/main/java/org/junit/internal/Classes.java, src/main/java/org/junit/internal/runners/statements/FailOnTimeout.java, src/main/java/org/junit/rules/ErrorCollector.java, src/main/java/org/junit/rules/ExpectedException.java, src/main/java/org/junit/runner/FilterFactories.java, src/main/java/org/junit/runner/JUnitCore.java, src/main/java/org/junit/runner/notification/SynchronizedRunListener.java, src/main/java/org/junit/runners/model/FrameworkMember.java
Used `./mvnw compile -Dmaven.compiler.showDeprecation=true` to identify the warnings.
=> Address some warnings (in 4 parts)
